name: Grivience
version: ${version}
main: io.papermc.Grivience.GriviencePlugin
api-version: "1.21"
description: Japanese-themed party dungeon runs inspired by SkyBlock-style floors.
author: Kazutos
softdepend: [AuraSkills, EcoEnchants]

commands:
  dungeon:
    description: Manage parties and run dungeon floors.
    usage: /dungeon help | /dungeon menu | /dungeon give <player> <item_id> [amount]
    aliases: [dg]
  party:
    description: Manage your dungeon party.
    usage: /party <create|invite|accept|leave|kick|list|finder>
    aliases: [p]

permissions:
  grivience.admin:
    description: Allows dungeon reload and admin operations.
    default: op
